from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 746)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.fileLoadTab = QtWidgets.QWidget()
        self.fileLoadTab.setObjectName("fileLoadTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fileLoadTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.fileLoadTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 22, 659, 80))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.herodataButton = QtWidgets.QPushButton(self.groupBox_3)
        self.herodataButton.setGeometry(QtCore.QRect(122, 10, 75, 23))
        self.herodataButton.setObjectName("herodataButton")
        self.herodataLabel = QtWidgets.QLabel(self.groupBox_3)
        self.herodataLabel.setGeometry(QtCore.QRect(10, 11, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.herodataLabel.setFont(font)
        self.herodataLabel.setObjectName("herodataLabel")
        self.heroDataEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.heroDataEdit.setGeometry(QtCore.QRect(210, 10, 400, 23))
        self.heroDataEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.heroDataEdit.setObjectName("heroDataEdit")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 37, 611, 31))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 107, 659, 80))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.artifactdataButton = QtWidgets.QPushButton(self.groupBox_5)
        self.artifactdataButton.setGeometry(QtCore.QRect(122, 10, 75, 23))
        self.artifactdataButton.setObjectName("artifactdataButton")
        self.artifactdataLabel = QtWidgets.QLabel(self.groupBox_5)
        self.artifactdataLabel.setGeometry(QtCore.QRect(10, 11, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.artifactdataLabel.setFont(font)
        self.artifactdataLabel.setObjectName("artifactdataLabel")
        self.artifactDataEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.artifactDataEdit.setGeometry(QtCore.QRect(210, 10, 400, 23))
        self.artifactDataEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.artifactDataEdit.setObjectName("artifactDataEdit")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(20, 38, 611, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 190, 659, 80))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.fribbelsButton = QtWidgets.QPushButton(self.groupBox_6)
        self.fribbelsButton.setGeometry(QtCore.QRect(122, 10, 75, 23))
        self.fribbelsButton.setObjectName("fribbelsButton")
        self.fribbelsLabel = QtWidgets.QLabel(self.groupBox_6)
        self.fribbelsLabel.setGeometry(QtCore.QRect(10, 11, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fribbelsLabel.setFont(font)
        self.fribbelsLabel.setObjectName("fribbelsLabel")
        self.fribbelsDataEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.fribbelsDataEdit.setGeometry(QtCore.QRect(210, 10, 400, 23))
        self.fribbelsDataEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.fribbelsDataEdit.setObjectName("fribbelsDataEdit")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(20, 38, 611, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.loadFileDataButton = QtWidgets.QPushButton(self.groupBox)
        self.loadFileDataButton.setGeometry(QtCore.QRect(53, 282, 241, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loadFileDataButton.setFont(font)
        self.loadFileDataButton.setObjectName("loadFileDataButton")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 345, 611, 31))
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.saveConfigButton = QtWidgets.QPushButton(self.groupBox)
        self.saveConfigButton.setGeometry(QtCore.QRect(350, 282, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveConfigButton.setFont(font)
        self.saveConfigButton.setObjectName("saveConfigButton")
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_7 = QtWidgets.QGroupBox(self.fileLoadTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.darkModeCheck = QtWidgets.QCheckBox(self.groupBox_7)
        self.darkModeCheck.setGeometry(QtCore.QRect(70, 30, 131, 17))
        self.darkModeCheck.setObjectName("darkModeCheck")
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_2 = QtWidgets.QGroupBox(self.fileLoadTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.jsonLogText = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.jsonLogText.setGeometry(QtCore.QRect(10, 30, 621, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.jsonLogText.sizePolicy().hasHeightForWidth())
        self.jsonLogText.setSizePolicy(sizePolicy)
        self.jsonLogText.setObjectName("jsonLogText")
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.fileLoadTab, "")
        self.heroTableTab = QtWidgets.QWidget()
        self.heroTableTab.setObjectName("heroTableTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.heroTableTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.heroTableTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.hideBadCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.hideBadCheckBox.setObjectName("hideBadCheckBox")
        self.verticalLayout_8.addWidget(self.hideBadCheckBox)
        self.heroViewList = QtWidgets.QTableWidget(self.groupBox_4)
        self.heroViewList.setObjectName("heroViewList")
        self.heroViewList.setColumnCount(0)
        self.heroViewList.setRowCount(0)
        self.verticalLayout_8.addWidget(self.heroViewList)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.heroTableTab, "")
        self.fileOutputTab = QtWidgets.QWidget()
        self.fileOutputTab.setObjectName("fileOutputTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fileOutputTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_8 = QtWidgets.QGroupBox(self.fileOutputTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.goButton = QtWidgets.QPushButton(self.groupBox_8)
        self.goButton.setGeometry(QtCore.QRect(20, 190, 611, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.goButton.setFont(font)
        self.goButton.setObjectName("goButton")
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setGeometry(QtCore.QRect(337, 110, 261, 40))
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.outputLocationButton = QtWidgets.QPushButton(self.groupBox_8)
        self.outputLocationButton.setGeometry(QtCore.QRect(116, 37, 75, 23))
        self.outputLocationButton.setObjectName("outputLocationButton")
        self.appDetailCheck = QtWidgets.QCheckBox(self.groupBox_8)
        self.appDetailCheck.setGeometry(QtCore.QRect(337, 100, 181, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.appDetailCheck.setFont(font)
        self.appDetailCheck.setChecked(False)
        self.appDetailCheck.setObjectName("appDetailCheck")
        self.previewCheck = QtWidgets.QCheckBox(self.groupBox_8)
        self.previewCheck.setGeometry(QtCore.QRect(37, 100, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.previewCheck.setFont(font)
        self.previewCheck.setChecked(False)
        self.previewCheck.setObjectName("previewCheck")
        self.outputLocationEdit = QtWidgets.QLineEdit(self.groupBox_8)
        self.outputLocationEdit.setGeometry(QtCore.QRect(200, 37, 400, 23))
        self.outputLocationEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.outputLocationEdit.setObjectName("outputLocationEdit")
        self.label_14 = QtWidgets.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(38, 120, 211, 20))
        self.label_14.setObjectName("label_14")
        self.outputLocationLabel = QtWidgets.QLabel(self.groupBox_8)
        self.outputLocationLabel.setGeometry(QtCore.QRect(20, 40, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.outputLocationLabel.setFont(font)
        self.outputLocationLabel.setObjectName("outputLocationLabel")
        self.verticalLayout_6.addWidget(self.groupBox_8)
        self.groupBox_15 = QtWidgets.QGroupBox(self.fileOutputTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_15.sizePolicy().hasHeightForWidth())
        self.groupBox_15.setSizePolicy(sizePolicy)
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.outputLogText = QtWidgets.QPlainTextEdit(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.outputLogText.sizePolicy().hasHeightForWidth())
        self.outputLogText.setSizePolicy(sizePolicy)
        self.outputLogText.setObjectName("outputLogText")
        self.horizontalLayout.addWidget(self.outputLogText)
        self.verticalLayout_6.addWidget(self.groupBox_15)
        self.tabWidget.addTab(self.fileOutputTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionExit)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Otherworldly Machinery"))
        self.groupBox.setTitle(_translate("MainWindow", "Files"))
        self.herodataButton.setText(_translate("MainWindow", "Browse"))
        self.herodataLabel.setText(_translate("MainWindow", "e7dbherodata.json"))
        self.label.setText(_translate("MainWindow", "This file contains data about all the heroes in Epic7.  By default a file is included with the relevant information, but you may need to replace it with a new file when a new content comes out."))
        self.artifactdataButton.setText(_translate("MainWindow", "Browse"))
        self.artifactdataLabel.setText(_translate("MainWindow", "artifactdata.json"))
        self.label_9.setText(_translate("MainWindow", "This file contains data about all the heroes in Epic7.  By default a file is included with the relevant information, but you may need to replace it with a new file when a new content comes out."))
        self.fribbelsButton.setText(_translate("MainWindow", "Browse"))
        self.fribbelsLabel.setText(_translate("MainWindow", "Fribbels Data"))
        self.label_10.setText(_translate("MainWindow", "This file is the storage file used by Fribbels Optimizer. This file is called autosave.json, and on windows is typically stored in a folder named FribbelsOptimizerSaves within Documents. "))
        self.loadFileDataButton.setText(_translate("MainWindow", "Load Data From JSON"))
        self.label_12.setText(_translate("MainWindow", "Once you\'ve clicked Load and is completed succesfully, your configurations will be saved for next time you run the software."))
        self.saveConfigButton.setText(_translate("MainWindow", "Save Configuration Data"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Config"))
        self.darkModeCheck.setText(_translate("MainWindow", "Dark Mode (test)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fileLoadTab), _translate("MainWindow", "Setup"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Heroes in File"))
        self.label_13.setText(_translate("MainWindow", "If this panel is empty, setup your files on the File Setup Tab. Otherwise, number the units in order of what you want them to be displayed in the infographic."))
        self.hideBadCheckBox.setText(_translate("MainWindow", "Hide Heroes with Issues"))
        self.heroViewList.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.heroTableTab), _translate("MainWindow", "Hero Picker"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Files"))
        self.goButton.setText(_translate("MainWindow", "Go!"))
        self.label_15.setText(_translate("MainWindow", "Remove the footer that gives details about how the image was generated."))
        self.outputLocationButton.setText(_translate("MainWindow", "Browse"))
        self.appDetailCheck.setText(_translate("MainWindow", "Remove App Detail Footer"))
        self.previewCheck.setText(_translate("MainWindow", "Show Preview"))
        self.label_14.setText(_translate("MainWindow", "Show a preview of the completed image"))
        self.outputLocationLabel.setText(_translate("MainWindow", "Output Location"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fileOutputTab), _translate("MainWindow", "Output File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

